### ISSUE TITLE
建议：api设计建议

### ISSUE THREAD

**Issue by fuchaosz** [saiwu-bigkoo/Android-AlertView#19]
建议api设计的时候保持和系统一致，尽量不要改变编码习惯，一行代码调用的api不太好用，那么多参数难凑，而且有些参数也并不是必须。
建议你把每种Dialog的名字换一下，用名字来区分不同的dialog,而不要用相同的名字不同的api来区分，毕竟记忆api是很蛋疼的事情，而且还那么多参数

**Comment by saiwu-bigkoo** [comment]
加入了builder模式，但不会考虑分开不同名字，这些参数其实是必要的，而且iOS的api也是这样。
