### ISSUE TITLE
不能显示在popupwindow之上吗？

### ISSUE THREAD

**Issue by hudan2714** [saiwu-bigkoo/Android-AlertView#24]
已经显示了一个popuwindow了。点击弹出一个alertview，就显示在popuwindow下面了（被遮盖了），不能显示在最上层吗？？？

**Comment by saiwu-bigkoo** [comment]
不能，这个是依附在Activity的根View上

**Comment by hudan2714** [comment]
有没有办法能改造下，使之能在传入的view上显示呢？

**Comment by saiwu-bigkoo** [comment]
自己改为Pop方式或ActivityDialog方式则可以
