### ISSUE TITLE
能否提供在代码中动态变更按钮文本的功能？

### ISSUE THREAD

**Issue by mazhewei** [saiwu-bigkoo/Android-AlertView#27]
如题

**Comment by jingchangfa** [comment]
+1 同求～
作者建议“避免创建重复View，先创建View，然后需要的时候show出来”
然而却没能提供更改文本的功能，怎么复用～

**Comment by saiwu-bigkoo** [comment]
当时没考虑那么多，仅仅按iOS的api实现。

**Comment by saiwu-bigkoo** [comment]
仔细想了想，没必要复用。一个页面你new 多几个不同的也是没有多大影响的，而且单一职责，没必要为了复用去改变文字。
