### ISSUE TITLE
minSdkVersion 能否支持9+

### ISSUE THREAD

**Issue by xuhuan** [saiwu-bigkoo/Android-AlertView#4]
现在的是14，看了Android-ConvenientBanner 和 Android-PickerView 也都是14，这是因为用到的api最低是14还是默认配置是14？如果可以支持更低版本的话能否把这个值调到最小，以适应更多的设备？

**Comment by saiwu-bigkoo** [comment]
嘿，已经改为9+了，ConvenientBanner 用到api是14+所以降不了。

**Comment by xuhuan** [comment]
因为用到的api原因降不了的没关系，就是能降到最低的是最低的就好了，这样适配设备能多一点，通用性也好一点。目前开发要考虑2.3+的，所以只能找支持低版本的，高版本的话就悲催来的。
谢谢了。
