### ISSUE TITLE
额，问下包提交到哪个仓库了

### ISSUE THREAD

**Issue by xuhuan** [saiwu-bigkoo/Android-AlertView#5]
在仓库没搜到这个包。
搜了下面两个仓库都没有。
http://maven.oschina.net/
http://search.maven.org/

**Comment by saiwu-bigkoo** [comment]
https://bintray.com/bintray/jcenter 在这个仓库呢。教程请看 http://saiwu-bigkoo.github.io/2015/10/02/android/

**Comment by xuhuan** [comment]
感谢回复。
