### ISSUE TITLE
希望加入自定义背景的接口

### ISSUE THREAD

**Issue by cikichen** [saiwu-bigkoo/Android-AlertView#6]
目前是固定的，希望能加入背景设置，宽度设置等的接口，目前没有接口，想要自定义，就没法使用gradle的自动依赖方式

**Comment by saiwu-bigkoo** [comment]
你可以通过重写xml和drawable里面相同名字的资源就可以覆盖掉原本的效果了。
    <dimen name="margin_alert_left_right">40dp</dimen>
    <dimen name="margin_actionsheet_left_right">10dp</dimen>

**Comment by 919317632** [comment]
我想问一下，如果要讲取消两个字的加粗效果去掉，是不是只能重写呢

**Comment by saiwu-bigkoo** [comment]
其实也可以通过重写同名xml达到目的

**Comment by 919317632** [comment]
actionsheet可以，但是alertview里加了这个'tvAlert.setTypeface(Typeface.DEFAULT_BOLD);'……
